apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: prod
  labels:
    app: nginx   # <-- labels belong here inside metadata
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


---

apiVersion: v1
kind: Service
metadata:
  name: java-hello-world-service
  namespace: prod
labels:
  app: java-hello-world
spec:
  selector:
    app: java-hello-world
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http




