apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: prod
  labels:
    app: nginx   # <-- labels belong here inside metadata
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP


---


apiVersion: v1
kind: Service
metadata:
  name: java-hello-world-service
  namespace: prod
spec:
  selector:
    app: java-hello-world  # Matches the label in the deployment
  ports:
    - protocol: TCP
      port: 80        # The port the service will expose
      targetPort: 8080 # The port the container is listening on
  type: ClusterIP     # You can change this to NodePort or LoadBalancer if needed






